//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagement1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class restaurantDB1Entities : DbContext
    {
        public restaurantDB1Entities()
            : base("name=restaurantDB1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<DepartedCustomers> DepartedCustomers { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Reservations> Reservations { get; set; }
        public virtual DbSet<Tables> Tables { get; set; }
    }
}
